<?php
namespace App\Http\Controllers;

use App\User;
use App\Offer;
use App\Saved;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/*
 * UserController provides views regarding management of the user,
 * including processing data from the POST requests from the sign up and sign in forms
 * also, profile is generated by the UserController as well
 */

class UserController extends Controller {

    public function postSignUp(Request $request) {
        $this -> validate($request, [
            'email_up' => 'required|email|unique:users,email',
            'name' => 'required|regex:/^[a-zA-Z]+$/u|max:120',
            'password' => 'required|min:5'
        ]);
        $email = $request['email_up'];
        $name = $request['name'];
        $password = bcrypt($request['password']);

        $user = new User();
        $user->email = $email;
        $user->name = $name;
        $user->password = $password;

        $user->save();

        Auth::login($user);

        return redirect()->route('dashboard');
    }

    public function postSignIn(Request $request) {
        $this -> validate($request, [
            'email_in' => 'required',
            'password' => 'required'
        ]);
        if (Auth::attempt(['email'=>$request['email_in'], 'password'=>$request['password']])) {
            //if (Auth::attempt(['email'=>$request['email']])) {
            return redirect()->route('dashboard');
        }
        $message = "Incorrect login information.";
        $is_error = 1;
        return redirect()->back()->with(['message' => $message, 'is_error' => $is_error]);
    }

    public function getLogOut() {
        Auth::logout();
        return redirect()->route('home');
    }

    public function getProfile() {
        $saved_off_ids_arr = Saved::where('user_id', '=', Auth::id())->pluck('offer_id');
        $saved_offers = Offer::whereIn('id', $saved_off_ids_arr)->get();
        $my_offers = Offer::where('user_id', '=', Auth::id() )->get();
        return view('profile', ['saved_offers' => $saved_offers, 'my_offers' => $my_offers]);
    }

}

